"""
Django settings for API project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#uc07jryn&8iu8$j3zq^5#5z-4uz_!(00sc&opragy+(-)r1hb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django_gulp',
    'authentication',
    'rest_framework',
    'rest_framework.authtoken',
    'allauth',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TNB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TNB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

AUTH_USER_MODEL='authentication.User'
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join('staticfiles')

STATICFILES_DIRS = [
    os.path.join("authentication", "static"),
    os.path.join("TNB", "static"),
]

# Authentication settings
REST_AUTH_TOKEN_MODEL = 'rest_framework.authtoken.models'
REST_AUTH_TOKEN_CREATOR = 'authentication.utils.default_create_token'
REST_AUTH_SERIALIZERS = {
    'LOGIN_SERIALIZER': 'authentication.api.serializers.UserLoginSerializer',
    'TOKEN_SERIALIZER': 'authentication.api.serializers.TokenSerializer',
    'REGISTER_SERIALIZER': 'authentication.api.serializers.UserCreateSerializer',
    'USERDETAILS_SERIALIZER': 'authentication.api.serializers.UserDetailsSerializer',
    'PASSWORD_CHANGE_SERIALIZER': 'authentication.api.serializers.PasswordChangeSerializer',
    'PASSWORD_RESET_SERIALIZER': 'authentication.api.serializers.PasswordResetSerializer',
    'PIN_CHANGE_SERIALIZER': 'authentication.api.serializers.PinChangeSerializer'
}

OLD_PASSWORD_FIELD_ENABLED = True
LOGOUT_ON_PASSWORD_CHANGE = False

DEFAULT_FROM_EMAIL = 'test@blockchaintmhub.io'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'test@blockchaintmhub.io'
EMAIL_HOST_PASSWORD = '432655test'
EMAIL_USE_TLS = True
MEDIA_URL = '/company_logo/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'company_logo')
# This is used for importing the local and production settings file
os.environ['DJANGO_SETTINGS_MODULE'] = 'TNB.settings.local'

